## Task 2 notes: neural networks

2 warstwy w tym zadaniu

90% dokładność

wariancja - r normalny z wariancją (std) < 1 (1/sqrt(ilości obs + bias))

aktualizowanie wag - back propagation

dodatkowe pkt:

podzielić dane na paczki, 

inne postacie funkcji aktywacji fi

lepsza implementacja (bardziej ogólna)

In [1]:
import numpy as np
from mnist_loader import load_data, load_data_wrapper, vectorized_result

In [ ]:
class NN:
    def __init__(self, training_data, layers=2, c=0.01, epoch=10):
        self.X = training_data[0]
        self.Y = training_data[1]
        
        self.input_size = self.X.shape[0]
        self.output_size = self.Y.shape[0]
        
        self.epochs = epoch
        self.c = c
        self.layers = layers
        
    def initiate_weight(self):
        wt = np.zeros((self.input_shape+1)*self.output_shape)
        for i in range(len(wt)):
            wt[i] = np.random.randn()
        return np.array(wt).reshape(self.output_shape, self.input_shape+1)
    
    def sigmoid(self):
        return (1/(1+np.exp(-x)))
    
    def forward_pass_one_layer(self, x, weight):
        X = np.concatenate(([1], X), axis=0)
        net = weight @ X
        a = self.sigmoid(net)
        
        return net, a
    
    def back_prop_one_layer(self, net, a, y, weight):
        X = np.concatenate(([1], a), axis=0)
        
        sig_val = [self.sigmoid(n) for n in net]
        sigmoid_derivative = sig_val*(1-sig_val)
        
        delta = np.multiply(a, sigmoid_derivative)
        derivative = delta @ X.T
        
        updated_weight = weight - self.c*derivative
        
        return updated_weight
    
    def forward_pass(self, x):
        activations = np.zeros(self.layers)
        layer_input = 
    
    def train(self):
        for j in range(len(self.input_size))
            for i in range(self.layers):
                
        

In [6]:
class NeuralNetwork:
    def __init__(self, X, Y, c = 0.01, epoch = 10):
        self.input = X
        
        self.input_size = X.shape[0]
        self.output
        
        self.sigmoid_values = {}
        self.epochs = epoch
        self.c = c
        
    def sigmoid_to_fix(self, x):
        if x in self.sigmoid_values:
            return self.sigmoid_values[x]
        else:
            value = (1/(1+np.exp(-x)))
            self.sigmoid_values[x] = value
            return value
    
    def sigmoid(self, x):
        return (1/(1+np.exp(-x)))
    
    def forward_pass(self, X, weight1, weight2):
        n, m = X.shape
        X = np.concatenate((np.ones((m, 1), dtype=int), X), axis=0)
        
        net1 = weight1 @ X
        a1 = self.sigmoid(net)
        
        n, m = a1.shape
        X2 = np.concatenate((np.ones((m, 1), dtype=int), a1), axis=0)
        
        net2 = weight2 @ X2
        a2 = self.sigmoid(net2)
        
        return a1, a2, net1, net2
    
    def loss_function(self, Y, ak):
        l = np.square(y-ak)
        return np.sum(l)
    
    def generate_weights(self, x, y):
        wt =[]
        for _ in range(x*y):
            wt.append(np.random.randn())
        return np.array(wt).reshape(x, y)
        
    
    def back_propagation(self, X, Y, weight1, weight2, c):
        a1, a2, net1, net2 = self.forward_pass(X, weight1, weight2)
        X = np.concatenate((np.ones((X.shape[1], 1), dtype=int), X), axis=0)
        
        dl_a2 = a2 - y
        sig_val2 = self.sigmoid(net2)
        sigmoid_derivative2 = sig_val2*(1-sig_val2)
        
        delta2 = np.multiply(dl_a2, sigmoid_derivative2)
        
        X2 = np.concatenate((np.ones((a1.shape[1], 1), dtype=int), a1), axis=0)
        dl_w2 = delta2 @ X2.T
        
        weight2_updated = weight2 - self.c*dl_w2
        
        dl_x = weight2.T @ delta2
        
        dl_a1 = np.delete(dl_x, 0, 0)
        sig_val1 = self.sigmoid(net1)
        sigmoid_derivative1 = sig_val1*(1-sig_val1)
        
        delta1 = np.multiply(dl_a1, sigmoid_derivative1)
        dl_w1 = delta1 @ X.T
        
        weight1_updated = weight1 - self.c*dl_w1
        
        return a1, a2, weight1_updated, weight2_updated
    
    def train(X, Y, weight1, weight2):
        accuracy = []
        loss = []
        for i in range(self.epochs):
            l = []
            for j in range(len(X)):
                a1, a2, weight1, weight2 = self.back_propagation(X, Y, weight1, weight2)
                l.append((loss(a2, Y[j])))
            print("Epochs: ", i+1)
            print("Accuracy: ", (1-(sum(l)/len(X)))*100)
            accuracy.append((1-(sum(l)/len(x)))*100)
            loss.append(sum(l)/len(x))
        return accuracy, loss, weight1, weight2
    
    def predict(X, weight1, weight2):
        _, a2, _, _ = self.forward_pass(X, weight1, weight2)
        for x, y in test_data:
            test_results.append((self.forward_pass(x, weight1, weight2)[1], y))
        return sum(int(x == y) for (x, y) in test_results)
            

In [7]:
X = np.array([[1, 0]]).T
Y = np.array([[1, 2, 0]]).T
n, m = X.shape
X = np.concatenate((np.ones((m, 1), dtype=int), X), axis=0)

In [8]:
X_new = np.delete(X, 0, 0)

In [9]:
X_new

array([[1],
       [0]])

In [10]:
X

array([[1],
       [1],
       [0]])

## Usage Tests

In [13]:
training_data, validation_data, test_data = load_data_wrapper()

In [15]:
x, y = zip(*training_data)

In [19]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
len(validation_data[0])

10000

In [12]:
NN = NeuralNetwork(training_data)

In [ ]:
w1 = NN.

In [13]:
import sklearn.datasets
X, Y = sklearn.datasets.make_moons(n_samples=500, noise=.2)

In [16]:
training_data

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([5, 0, 4, ..., 8, 4, 8], dtype=int64))